export const requests = [
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
  {
    id: 1,
    studentName: "John Doe",
    message: "request to be tutored",
    start_date: "20-11-2023",
    end_date: "20-11-2023",
    start_time: "9:45AM",
    period: "1hr",
    areaOfInterest: "mathematics",
  },
];
